// actions
export const ADD_PACK = 'ADD_PACK'
export const UPDATE_PACK = 'UPDATE_PACK'

export const ADD_BOOKING = 'ADD_BOOKING'
export const REMOVE_BOOKING = 'REMOVE_BOOKING'

export const RECEIVE_REQUESTS = 'RECEIVE_REQUESTS'
export const ADD_BOOKING_REQUEST = 'ADD_BOOKING_REQUEST'
export const REMOVE_BOOKING_REQUEST = 'REMOVE_BOOKING_REQUEST'

export const ADD_USER = 'ADD_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const REMOVE_USER = 'REMOVE_USER'

export const ADD_SALON = 'ADD_SALON'
export const UPDATE_SALON = 'UPDATE_SALON'

export const ADD_SALON_APPROVE = 'ADD_SALON_APPROVE'
export const UPDATE_SALON_APPROVE = 'UPDATE_SALON_APPROVE'

// mode Actions
export const SET_MODE_LOADING = 'SET_MODE_LOADING'
export const SET_MODE_READY = 'SET_MODE_READY'

// modes
export const MODE_LOADING = 'MODE_LOADING'
export const MODE_READY = 'MODE_READY'
export const MODE_INIT = 'MODE_INIT'

// ZIP
export const RECEIVE_WAIT_LIST = 'RECEIVE_WAIT_LIST'
export const UPDATE_WAIT_LIST_RECORD = 'UPDATE_WAIT_LIST_RECORD'
export const REMOVE_WAIT_LIST_RECORD = 'REMOVE_WAIT_LIST_RECORD'

//AREAS
export const RECEIVE_AREAS = 'RECEIVE_AREAS'
export const UPDATE_AREA = 'UPDATE_AREA'
export const REMOVE_AREA = 'REMOVE_AREA'

//LOADERS
export const GOOGLE_MAPS_API_LOADED = 'GOOGLE_MAPS_API_LOADED'
